## Creating  a Logistic Regression to predict Absenteeism

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed=pd.read_csv('C:\\Users\\Hiral\\Downloads\\Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [4]:
#we take all the inputs to predict the absenteeism

# Logistic Regression is a type of classification so we classify people into classes and we need to find out these classes

In [5]:
#the people will be classified in 2 classes who are excessively absent and who have been moderately absent so we take the median of absenteeism in hours and below it will be normal and above it will be excessive
data_preprocessed['Absenteeism Time in Hours'].median()
#so if employee is absent for less than 3 hours then we assign it as 0 and if for more than 3 hours then 1 and our task will be to predict whether we obtain a 0 or a 1 and those are our targets

3.0

In [6]:
#variable targets which will measure if a person has been absent for more than 3 hours
#we use numpy where method i.e. condition , value if true and value if false it checks if condition is satisfied and assigns a value accordingly 
targets=np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data_preprocessed['Excessive Absenteeism']=targets

In [9]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0                 30          0         2    1                          4   
1                 31          0         1    0                          0   
2                 31          0         0    0                          2   
3                 24          0         2    0                          4   
4                 30          0         2    1                          2   
..               ...        ...       ...  ...                        ...   
695               22          1         2    0                          8   
696               24          0         1    2                          3   
697               25          1         0    0                          8   
698               25          1         0    0                          2   
699               25          0         1    1                          2   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 16 columns]

In [10]:
#by using median as a cutoff line we have balanced our dataset , roughly half of the targets are 0 and other half as 1 this will prevent our model from learning to outpou ONLY 0 or ONLY 1 in order to prove that we divide the 1 targets by total no. of targets
#total number of targets are calculated by targets.shape[0](no. of targets on axis 0)
targets.sum()/targets.shape

array([0.45571429])

In [11]:
targets.sum()/targets.shape[0]
#our 2 groups have been distributed roughly equally 

0.45571428571428574

In [12]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week','Daily Work Load Average','Distance to Work'],axis=1)

In [13]:
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                       289   33               30          0         2    1   
1                       118   50               31          0         1    0   
2                       179   38               31          0         0    0   
3                       279   39               24          0         2    0   
4                       289   33               30          0         2    1   
..                      ...  ...              ...        ...       ...  ...   
695                     179   40               22          1         2    0   
696                     225   28               24          0         1    2   
697                     330   28               25          1         0    0   
698                     235   32               25          1         0    0   
699                     291   40               25          0         1    1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [14]:
#is is a reserved word that returs true if 2 variables refer to same object and false if not
data_with_targets is data_preprocessed

False

In [15]:
#selecting the inputs for regression and we use the iloc method for it and it selects by position in the data frame it takes row indices and column indices as arguements
data_with_targets.shape

(700, 12)

In [16]:
targets.shape

(700,)

In [17]:
#so we select all rows and columns except excessive absenteeism as its the target
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                       289   33               30          0         2    1   
1                       118   50               31          0         1    0   
2                       179   38               31          0         0    0   
3                       279   39               24          0         2    0   
4                       289   33               30          0         2    1   
..                      ...  ...              ...        ...       ...  ...   
695                     179   40               22          1         2    0   
696                     225   28               24          0         1    2   
697                     330   28               25          1         0    0   
698                     235   32               25          1         0    0   
699                     291   40               25          0         1    1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [18]:
#these are the required inputs
unscaled_inputs=data_with_targets.iloc[:,:-1]

In [19]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
0                       289   33               30          0         2    1  
1                       118   50               31          0         1    0  
2                       179   38               31          0         0    0  
3                       279   39               24          0         2    0  
4                       289   33               30          0         2    1  
..                      ...  ...              ...        ...       ...  ...  
695                     179   40               22          1         2    0  
696                     225   28               24          0         1    2  
697                     330   28               25          1         0    0  
698                     235   32               25          1         0    0  
699                     291   40               25          0         1    1  

[700 rows x 11 columns]

# Standardize the data

In [20]:
#preprocessing.scale
#from sklearn.preprocessing import StandardScaler
#this object will be used to scale our data i.e it will subtract the mean and divide by standardd deviation in every feature
#absenteeism_scaler=StandardScaler()

In [21]:
#when we standardized the inputs we standardised the dummies as well which is bad bcz when we standardize we lose what the dummy wanted to actually interpret 
#if we could have left them in 0s and 1s we could have said for a unit change it is 7.92 times that the person will be excessively absent and a unit change in terms of dummy means disregarding this dummy to taking only this dummy in account(photo)
#so when reason_1 is given we can say it is 7.92 times that person will be absent compared to no reason given
#dummies became uninterpretable when we standardised as we lost how to compare different reasons as reasons are imp reasons
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler(BaseEstimator,TransformerMixin): 
    #this has an arguement columns that takes which columns to scale
    #NO NEED TO UNDERSTAND CODE JUST KNOW HOW TO USE IT
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None
 
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.array(np.mean(X[self.columns]))
        self.var_ = np.array(np.var(X[self.columns]))
        return self
 
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), 
        columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [22]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [23]:
#columns_to_scale=[ 'Month Value',
#       'Day of the Week', 'Transportation Expense', 'Distance to Work',
 #      'Age', 'Daily Work Load Average', 'Body Mass Index', 
 #      'Children', 'Pet']
#after removing 'Day of the Week','Daily Work Load Average','Distance to Work we get error awe defined them to standardize so to encounter it
columns_to_omit=['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']
#instead of removing manually we use list function
columns_to_scale=[x for x in unscaled_inputs.columns.values if x not in columns_to_omit]
#here list works like a loop and takes all values that are not part of columns to omit

In [24]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [25]:
#this line will calculate the means and stanard deviation of each feature from unscaled_inputs and this info will be stored in absenteeism scaler object so it wont be an empty object anymore as it will contain info about mean and standard deviation
#this is important because whenever we get  new data we will know that standardization info is contained in absenteeism scaler object
absenteeism_scaler.fit(unscaled_inputs),absenteeism_scaler.get_params()


(CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                       'Body Mass Index', 'Children', 'Pet']),
 {'columns': ['Month Value',
   'Transportation Expense',
   'Age',
   'Body Mass Index',
   'Children',
   'Pet']})

In [26]:
#so we have the information but the inputs are still unscaled so its just "scaling mechanism" but we need to apply it in order to get scaled inputs so we use trandform method
#so as the absenteeism scaler has mean deviation so transform peroform the calcuations and whenever we get new data we apply this method to transform it
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)

In [27]:
scaled_inputs
#as we can see our dummies remains same

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.568019   
696         1         0         0         0    -0.568019   
697         1         0         0         0    -0.568019   
698         0         0         0         1    -0.568019   
699         0         0         0         1    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

          Pet  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

# Splitting Data for Training and Testing

In [28]:
from sklearn.model_selection import train_test_split
#train test split mainly takes inputs and targets as arguements

In [29]:
train_test_split(scaled_inputs,targets)
#so basically we get 4 arrays traindataset with inputs
# '' with targets
#test dataset with inputs
#'' with targets

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 110         0         0         0         1     1.228426   
 628         0         0         0         1     1.527833   
 120         0         0         0         1     0.330204   
 241         0         0         1         0     0.030796   
 440         0         0         0         1    -0.568019   
 ..        ...       ...       ...       ...          ...   
 309         0         0         0         1     0.929019   
 594         0         0         1         0     1.527833   
 143         0         0         0         1     1.527833   
 292         0         0         0         1    -0.268611   
 52          0         0         0         1     0.330204   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 110               -1.574681  0.091435         0.297027          0 -0.919030   
 628                0.190942 -0.692937        -0.408580          1 -0.919030   
 120                0.0400

In [30]:
#let there be 4 variables that contain 4 outputs
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,test_size=0.2,random_state=20)
#shuffle is by default set to true as when we re run the code we get a different set of output but this causes the final moel to be dufferent everytine and it changes accuracy so we use random state

In [31]:
print(x_train.shape,y_train.shape)
#training inputs are 525 obs aling 14 variables and targets are vector of length 525 and the latter corresponds to excessive absenteeism (75%,25%)

(560, 11) (560,)


In [32]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


# Model 


In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [34]:
reg=LogisticRegression()

In [35]:
#this gives us all the default parameters
reg.fit(x_train,y_train),reg.get_params()

(LogisticRegression(),
 {'C': 1.0,
  'class_weight': None,
  'dual': False,
  'fit_intercept': True,
  'intercept_scaling': 1,
  'l1_ratio': None,
  'max_iter': 100,
  'multi_class': 'auto',
  'n_jobs': None,
  'penalty': 'l2',
  'random_state': None,
  'solver': 'lbfgs',
  'tol': 0.0001,
  'verbose': 0,
  'warm_start': False})

In [36]:
reg.score(x_train,y_train)
#means model has 76% accuray

0.7767857142857143

## Calculating accuracy manually

In [37]:
#accuracy means how many outputs match the targets
#so to find accuracy manually we find the outputs and ccompare them to targets
model_outputs=reg.predict(x_train)
model_outputs
#comparing both

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [38]:
#the following method returns true for same values and false for opposite
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [39]:
model_outputs.shape

(560,)

In [40]:
#as we know true=1 so lets find sum of true values
accurate_outputs=np.sum(model_outputs==y_train)

In [41]:
accurate_outputs

435

In [70]:
accurate_outputs/model_outputs.shape[0]

0.7767857142857143

In [43]:
#interceplt
#intercept is a single number thats why it gets changed when we ad [0] after it
reg.intercept_[0]

-1.6095747087355274

In [44]:
reg.coef_

array([[ 2.77151176,  0.93168817,  3.09210221,  0.8090592 ,  0.00781237,
         0.62505482, -0.17390339,  0.28829409, -0.24081615,  0.35753531,
        -0.27337422]])

In [51]:
#whenever we employ sklearn the results are arrays not dataframes
#with statsmodel all manipulations go thru pandas
scaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [52]:
#we standardised the data frame unscaled inputs using standard scaler and was stored in scaled inputs this shows that sklearn is compatible with pandas dataframe BUT whenever we apply SKLEARN Function everything is transfored to nd array such as inputs,coef and intercept
#so we use unscaled inputs to find column names
feature_name=unscaled_inputs.columns.values

In [53]:
#to display which feature contains which coef and intercept we need a dataframe
summary_table=pd.DataFrame(columns=['feature_name'],data=feature_name)
summary_table['Coefficinet']=reg.coef_

ValueError: Length of values (1) does not match length of index (11)

In [54]:
#we got this error because by default nd arrays are rows not columns so we need to transpose it
summary_table=pd.DataFrame(columns=['feature_name'],data=feature_name)
summary_table['Coefficinet']=np.transpose(reg.coef_)

In [55]:
summary_table

feature_name  Coefficinet
0                 Reason_1     2.771512
1                 Reason_2     0.931688
2                 Reason_3     3.092102
3                 Reason_4     0.809059
4              Month Value     0.007812
5   Transportation Expense     0.625055
6                      Age    -0.173903
7          Body Mass Index     0.288294
8                Education    -0.240816
9                 Children     0.357535
10                     Pet    -0.273374

In [56]:
#we need to add the intercept at top but there is no method to do it so we shift all indices by 1 so as 0th index becomes empty we put intercept there using loc method
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0].item()]
#photo(error)
#summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

feature_name  Coefficinet
0                Intercept    -1.609575
1                 Reason_1     2.771512
2                 Reason_2     0.931688
3                 Reason_3     3.092102
4                 Reason_4     0.809059
5              Month Value     0.007812
6   Transportation Expense     0.625055
7                      Age    -0.173903
8          Body Mass Index     0.288294
9                Education    -0.240816
10                Children     0.357535
11                     Pet    -0.273374

In [57]:
#standardised coefficients means coefficient of regression where all variables have been standardised
#whichever weight is bigger its corresponding feature is more important
#coefficients are log odds means all coefficients refer to log odds
#exponential of coeff column
summary_table['Odds']=np.exp(summary_table.Coefficinet)

In [58]:
summary_table

feature_name  Coefficinet       Odds
0                Intercept    -1.609575   0.199973
1                 Reason_1     2.771512  15.982778
2                 Reason_2     0.931688   2.538791
3                 Reason_3     3.092102  22.023327
4                 Reason_4     0.809059   2.245794
5              Month Value     0.007812   1.007843
6   Transportation Expense     0.625055   1.868348
7                      Age    -0.173903   0.840378
8          Body Mass Index     0.288294   1.334150
9                Education    -0.240816   0.785986
10                Children     0.357535   1.429801
11                     Pet    -0.273374   0.760808

In [59]:
#You've forgotten [0] of reg.intercept_[0]. Note that reg.intercept_ is an array with one value and you should assign the value, not the array:

#summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

In [60]:
summary_table.sort_values('Odds',ascending=False)
#odds=odds_ratio

feature_name  Coefficinet       Odds
3                 Reason_3     3.092102  22.023327
1                 Reason_1     2.771512  15.982778
2                 Reason_2     0.931688   2.538791
4                 Reason_4     0.809059   2.245794
6   Transportation Expense     0.625055   1.868348
10                Children     0.357535   1.429801
8          Body Mass Index     0.288294   1.334150
5              Month Value     0.007812   1.007843
7                      Age    -0.173903   0.840378
9                Education    -0.240816   0.785986
11                     Pet    -0.273374   0.760808
0                Intercept    -1.609575   0.199973

In [61]:
#feature with coeff around 0 and odds around 1 is not imp
#for 1 unit change in standardized feature the odds(NOT THE ONE WE USED) increase by the multiple equal to odds(WE USED,odds_ratio in module)(1=no change) so if odds ratio 
#e.g if odds=5:1 and odds ratio= 2 then new odds=10:1 as we multiplied by odds ratio
#e.g.daily work load avg is useless
#our baseline model(WHERE NO REASON GIVEN) is reason 0 where no reason is given so for e.g. a person with reason 1 is 16 times more likely to be excessively absent than a person who didnt specify a reason
#standardization increases the accuracy but decreses interpretibility (e.g. transportation expense) but since we predict we perform standardization
#for pets base model is no pet and its negative so for each additional standardised unit of pets odds are 1-0.75=0.25 lower thanbasemodel means several pets but not taking care by own

In [ ]:
#backward elimination(PHOTO) so we drop day of week,daily work load avg and distance to work and we see that we obtain same result even after dropping variablrs

# TESTING 

In [62]:
reg.score(x_test,y_test)
#73.6 percent accurate
#test accuracy always < train accuracy
#if there is a significant diff then overfitting

0.7357142857142858

In [63]:
#predict proba method doesnt give the output as o or 1 but the probability of output being 0 or 1
predicted_proba=reg.predict_proba(x_test)

In [64]:
predicted_proba
#it gives 2 columns 1st column is probability of being 0 and 2nd is of being 1
#summing any 2 columns horiz will give the value 1

array([[0.75466347, 0.24533653],
       [0.60917591, 0.39082409],
       [0.48329093, 0.51670907],
       [0.75768232, 0.24231768],
       [0.08357741, 0.91642259],
       [0.3052464 , 0.6947536 ],
       [0.303675  , 0.696325  ],
       [0.11636888, 0.88363112],
       [0.7400284 , 0.2599716 ],
       [0.75596036, 0.24403964],
       [0.50609784, 0.49390216],
       [0.19501503, 0.80498497],
       [0.06248668, 0.93751332],
       [0.7055465 , 0.2944535 ],
       [0.29675526, 0.70324474],
       [0.52028649, 0.47971351],
       [0.50551315, 0.49448685],
       [0.50843643, 0.49156357],
       [0.36713074, 0.63286926],
       [0.06422143, 0.93577857],
       [0.73822433, 0.26177567],
       [0.75768232, 0.24231768],
       [0.47994423, 0.52005577],
       [0.47760936, 0.52239064],
       [0.22619725, 0.77380275],
       [0.74047815, 0.25952185],
       [0.51148533, 0.48851467],
       [0.87702735, 0.12297265],
       [0.24005377, 0.75994623],
       [0.75768232, 0.24231768],
       [0.

In [66]:
predicted_proba.shape

(140, 2)

In [67]:
#we want prbability of excessive absenteeism means probability of 1 so we take out the values from column 2
predicted_proba[:,1]

array([0.24533653, 0.39082409, 0.51670907, 0.24231768, 0.91642259,
       0.6947536 , 0.696325  , 0.88363112, 0.2599716 , 0.24403964,
       0.49390216, 0.80498497, 0.93751332, 0.2944535 , 0.70324474,
       0.47971351, 0.49448685, 0.49156357, 0.63286926, 0.93577857,
       0.26177567, 0.24231768, 0.52005577, 0.52239064, 0.77380275,
       0.25952185, 0.48851467, 0.12297265, 0.75994623, 0.24231768,
       0.38859882, 0.71238179, 0.69821485, 0.49507156, 0.24231768,
       0.59772596, 0.26042186, 0.78022686, 0.4398591 , 0.60641126,
       0.24188848, 0.49713003, 0.25862385, 0.40689715, 0.80759194,
       0.59889345, 0.71944702, 0.24317762, 0.24676126, 0.2414598 ,
       0.50180816, 0.29299268, 0.6947536 , 0.24459387, 0.82033268,
       0.39193844, 0.90599346, 0.26442957, 0.32150234, 0.3220128 ,
       0.70502976, 0.69623972, 0.26579672, 0.77584327, 0.24541121,
       0.24490372, 0.07551158, 0.26087263, 0.76176924, 0.29640101,
       0.25772789, 0.31539593, 0.88408057, 0.4387068 , 0.59547

# saving the model=saving reg object as it contains all imp info
## Save the model

In [71]:
#pickle module is used in python is used to convert python object in character stream and this character stream will contain sufficient info and when we want to convert it back from character stram to python obj we unpickle it
#so basically we save reg variable into file so that in future we cn use it
import pickle

In [72]:
with open('model','wb') as file:
    pickle.dump(reg,file)
    #model=file name
    #wb=write bytes
    #when we pickle we dump the info in file an we unpickle we load it

In [74]:
#we need to save absenteeism scaler too as info in absenteeism scaler as its used to preprocess any new data
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)

In [75]:
#deployment of model is making it availible and ready to use which consists of 2 steps saving the model and applying to new data
#so we focus on step 2 and we store the code in module as storing code in module will allow us to reuse it without trouble

x
